tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-container": "#eeeeee",
                    "on-surface-variant": "#4f453e",
                    "on-tertiary": "#ffffff",
                    "on-primary-fixed-variant": "#5c412c",
                    "on-secondary-fixed-variant": "#4d463b",
                    "background": "#f9f9f9",
                    "on-background": "#1a1c1c",
                    "primary-fixed": "#ffdcc3",
                    "secondary-fixed": "#ede1d2",
                    "on-error": "#ffffff",
                    "surface-container-lowest": "#ffffff",
                    "surface-dim": "#dadada",
                    "surface-variant": "#e2e2e2",
                    "primary-fixed-dim": "#e5bfa3",
                    "inverse-surface": "#2f3131",
                    "surface": "#f9f9f9",
                    "error": "#ba1a1a",
                    "on-primary-fixed": "#2b1705",
                    "surface-bright": "#f9f9f9",
                    "inverse-on-surface": "#f0f1f1",
                    "surface-container-highest": "#e2e2e2",
                    "outline-variant": "#d3c4ba",
                    "surface-tint": "#755841",
                    "on-secondary": "#ffffff",
                    "on-primary": "#ffffff",
                    "tertiary-container": "#3c2000",
                    "on-secondary-container": "#6a6156",
                    "secondary-container": "#eadecf",
                    "tertiary": "#1f0e00",
                    "secondary": "#655d51",
                    "tertiary-fixed": "#ffdcbd",
                    "error-container": "#ffdad6",
                    "secondary-fixed-dim": "#d0c5b6",
                    "primary-container": "#38220f",
                    "on-secondary-fixed": "#201b12",
                    "on-surface": "#1a1c1c",
                    "on-primary-container": "#a9876e",
                    "on-tertiary-fixed-variant": "#623f18",
                    "surface-container-low": "#f3f3f4",
                    "outline": "#81756c",
                    "on-error-container": "#93000a",
                    "on-tertiary-fixed": "#2c1600",
                    "inverse-primary": "#e5bfa3",
                    "surface-container-high": "#e8e8e8",
                    "primary": "#200e01",
                    "on-tertiary-container": "#b28557",
                    "tertiary-fixed-dim": "#f0bd8b"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "margin-desktop": "64px",
                    "margin-mobile": "20px",
                    "container-max": "1280px",
                    "base": "8px",
                    "gutter": "24px"
            },
            "fontFamily": {
                    "headline-md": ["Montserrat"],
                    "headline-xl": ["Montserrat"],
                    "headline-lg": ["Montserrat"],
                    "body-sm": ["Montserrat"],
                    "body-lg": ["Montserrat"],
                    "body-md": ["Montserrat"],
                    "headline-xl-mobile": ["Montserrat"],
                    "label-bold": ["Montserrat"]
            },
            "fontSize": {
                    "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
                    "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "500"}],
                    "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
                    "headline-xl-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
                    "label-bold": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}]
            }
          },
        },
      }
